### PR TITLE
Add bsdmainutils & dnsutils packages

### PR DESCRIPTION
**Pull request by aaronbrooks-gh**
Adds the bsdmainutils package, which provides hexdump.

### CODE REVIEW

**Comment by aaronbrooks-gh** [comment]
Resolves

> --> Testing protocols (via openssl, SSLv2 via sockets)
> 
> SSLv2      /usr/local/bin/testssl/testssl.sh: line 2394: hexdump: command not found

**Comment by MatthewVance** [comment]
@promythyus thanks for the help. Before I merge this pull request in, do you care to re-order the new packages so they stay in alphabetical order? I know it's a small thing, but it makes scanning the list of packages easier. I don't mind doing it, but I wanted to make sure you get the credit for the patch. Basically, the code would look like: 

``` Dockerfile
RUN set -x \
  && apt-get update && apt-get install -y --no-install-recommends \
        bsdmainutils \
        ca-certificates \
        curl \
        dnsutils \
  && rm -rf /var/lib/apt/lists/* \
```

Also, one of us should also remove the known issues section from the [README.md](https://github.com/MatthewVance/testssl-docker/blob/master/README.md) file since the dnsutils package resolves issue #1. Ideally, this would occur in the _Add dnsutils package_ commit to help keep the history clean and all related changes together.

**Comment by aaronbrooks-gh** [comment]
@MatthewVance Sounds good to me. I think I've amended the "Add dnsutils package" commit in the correct fashion.

Thanks :)

**Comment by MatthewVance** [comment]
@promythyus Thanks so much! I just merged the pull request.

**Pull request merged**
